services:
  postgres:
    image: postgres
    volumes:
      - ./dataset/simple_store.sql:/docker-entrypoint-initdb.d/simple_store.sql
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "dbpwd123@@"
    ports:
      - "5532:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 10
  
  console-app:
    build: .
    hostname: simple-store
    image: simple-store-app
    depends_on:
      postgres:
        condition: service_healthy
    links:
      - postgres

