services:
  postgres:
    image: postgres
    volumes:
      - ./dataset/simple_store.sql:/docker-entrypoint-initdb.d/simple_store.sql
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "dbpwd123@@"
    ports:
      - "5532:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 10

  web-app:
    build: .
    hostname: simplestore
    image: simple-store-app
    depends_on:
      postgres:
        condition: service_healthy
    links:
      - postgres

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web-app
    links:
      - web-app

networks:
  default:
    driver: bridge
    name: simple-store